<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WhisperPete.Core\WhisperPete.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="10.0.3" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.22.2" />
    <None Update="app_icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="app_icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="CopyToLocalAppData" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <ItemGroup>
      <FilesToCopy Include="$(TargetDir)\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(FilesToCopy)" DestinationFolder="$(LocalAppData)\WhisperPete\%(RecursiveDir)" />
  </Target>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>WhisperPete.Tray</RootNamespace>
    <AssemblyName>WhisperPete.Tray</AssemblyName>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Version>0.5.0</Version>
    <ApplicationIcon>app_icon.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
